/**
 * \file rtkheadertestfooter.cxx
 *
 * \brief This test includes all headers for coverage and style purposed.
 *
 * This is the footer only of the file, the rest is generated by cmake and
 * includes all headers in the code subdirectory.
 *
 * \author Simon Rit
 */

int main(int , char**)
{ 
  std::cout << "\n\nTest PASSED! " << std::endl;
  return EXIT_SUCCESS;
}
