SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE "my.cdash.org")
SET(CTEST_DROP_LOCATION "/submit.php?project=RTK")
SET(CTEST_DROP_SITE_CDASH TRUE)
SET(CTEST_PROJECT_NAME "RTK")
SET(CTEST_NIGHTLY_START_TIME "1:00:00 UTC")

