#PBS -N rtk_dashboard
#PBS -l walltime=05:59:00,nodes=1:ppn=8,mem=10gb
#PBS -o /home/srit/tmp/rtk_dashboard.out
#PBS -e /home/srit/tmp/rtk_dashboard.err
#PBS -q gpu
#PBS -W x=GRES:gpu@1
set -x

export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8

/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda40_itk4.cmake
rm -fr /tmp/RTK_dashboard
mkdir /tmp/RTK_dashboard
git clone git://github.com/SimonRit/RTK.git /tmp/RTK_dashboard/RTK
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda41_itk4.cmake
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda42_itk4.cmake
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda50_itk4.cmake
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda60_itk4.cmake
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda70_itk4.cmake
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda70_itk4_sharedlibs.cmake
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk4.cmake -V
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_nocuda_system_itk4.cmake -V
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk4_simplertk.cmake -V
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_nocuda_system_itk4_simplertk.cmake -V
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk4_cov.cmake -V
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk4_nofftw.cmake -V
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk4_valgrind.cmake -V
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_nocuda_system_itk4_valgrind.cmake -V
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk490.cmake -V

export PATH=/home/srit/src/cmake/lin64-dg-v284/bin:$PATH
/bin/time ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk4_cmake284.cmake -V

export PATH=/home/srit/src/cmake/lin64-dg-v312-gcc450/bin:$PATH
ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc450_cuda40_itk4.cmake -V
ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc454_cuda40_itk4.cmake -V
ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc472_cuda40_itk4.cmake -V
ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk420.cmake -V
ctest -VV -S /home/srit/src/rtk/rtk-dashboard/linux15_fedora_gcc_cuda_system_itk460.cmake -V

# Generate a script to perform a cuda-memcheck on all tests
grep Command /tmp/RTK_dashboard/RTK_lin64_gcc_cuda_system_itk4/Testing/Temporary/LastTest_*.log | sed 's/Command:/cuda-memcheck --error-exitcode 1/g' > /tmp/RTK_dashboard/cudamemchecks.sh
