/*
 * File automatically generated by
 * gengen 1.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "reset_group.h"

void
reset_group_gen_class::generate_reset_group(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  stream << "static void";
  stream << "\n";
  stream << indent_str;
  stream << "reset_group_";
  generate_string (name, stream, indent + indent_str.length ());
  stream << "(struct ";
  generate_string (args_info, stream, indent + indent_str.length ());
  stream << " *args_info)";
  stream << "\n";
  stream << indent_str;
  stream << "{";
  stream << "\n";
  stream << indent_str;
  stream << "  if (! args_info->";
  generate_string (name, stream, indent + indent_str.length ());
  stream << "_group_counter)";
  stream << "\n";
  stream << indent_str;
  stream << "    return;";
  stream << "\n";
  stream << indent_str;
  indent = 2;
  stream << "  ";
  indent = 0;
  stream << "\n";
  stream << indent_str;
  indent = 2;
  stream << "  ";
  generate_string (body, stream, indent + indent_str.length ());
  indent = 0;
  stream << "\n";
  stream << indent_str;
  stream << "  args_info->";
  generate_string (name, stream, indent + indent_str.length ());
  stream << "_group_counter = 0;";
  stream << "\n";
  stream << indent_str;
  stream << "}";
  stream << "\n";
  stream << indent_str;
  stream << "\n";
  stream << indent_str;
}
