/*
 * File automatically generated by
 * gengen 1.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef UPDATE_GIVEN_GEN_CLASS_H
#define UPDATE_GIVEN_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class update_given_gen_class
{
 protected:
  string option_var_name;

 public:
  update_given_gen_class()
  {
  }
  
  update_given_gen_class(const string &_option_var_name) :
    option_var_name (_option_var_name)
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  void set_option_var_name(const string &_option_var_name)
  {
    option_var_name = _option_var_name;
  }

  void generate_update_given(ostream &stream, unsigned int indent = 0);
  
};

#endif // UPDATE_GIVEN_GEN_CLASS_H
