/* xbase/xbconfig.h.  Generated by configure.  */
/* xbase/xbconfig.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* HAVE_EXCEPTIONS */
/* #undef HAVE_EXCEPTIONS */

/* Define to 1 if you have the `fcntl' function. */
#define HAVE_FCNTL 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have the `vsprintf' function. */
#define HAVE_VSPRINTF 1

/* Name of package */
#define PACKAGE "xbase"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "xdb-devel@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "xbase"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "xbase 2.1.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "xbase"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.1.1"

#define PATH_SEPARATOR '/'

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "2.1.1"

/* XB_CASTELLANO */
/* #undef XB_CASTELLANO */

#define XB_DBT_BLOCK_SIZE 512

/* XB_DEBUG */
#define XB_DEBUG 1

/* XB_EXPRESSIONS */
#define XB_EXPRESSIONS 1

/* XB_FILTERS */
#define XB_FILTERS 1

/* XB_HTML */
#define XB_HTML 1

/* XB_INDEX_ANY */
#define XB_INDEX_ANY 1

/* XB_INDEX_NDX */
#define XB_INDEX_NDX 1

/* XB_INDEX_NTX */
#define XB_INDEX_NTX 1

/* XB_LOCKING_ON */
#define XB_LOCKING_ON 0

/* XB_MEMO_FIELDS */
#define XB_MEMO_FIELDS 1

/* XB_REAL_DELETE */
#define XB_REAL_DELETE 1

/* Define to 1 if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* # undef _ALL_SOURCE */
#endif

/* Define to 1 if on MINIX. */
/* #undef _MINIX */

/* Define to 2 if the system does not provide POSIX.1 features except with
   this defined. */
/* #undef _POSIX_1_SOURCE */

/* Define to 1 if you need to in order for `stat' and other things to work. */
/* #undef _POSIX_SOURCE */
