/*
 * File automatically generated by
 * gengen 1.4.1 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef CUSTOM_GETOPT_GEN_GEN_CLASS_H
#define CUSTOM_GETOPT_GEN_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class custom_getopt_gen_gen_class
{
 protected:

 public:
  custom_getopt_gen_gen_class()
  {
  }
  

  void generate_custom_getopt_gen(ostream &stream, unsigned int indent = 0);
  
};

#endif // CUSTOM_GETOPT_GEN_GEN_CLASS_H
