/*
 * File automatically generated by
 * gengen 1.4.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "enum_decl.h"

void
enum_decl_gen_class::generate_enum_decl(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  stream << "enum enum_";
  generate_string (var_arg, stream, indent + indent_str.length ());
  stream << " { ";
  generate_string (var_arg, stream, indent + indent_str.length ());
  stream << "__NULL = -1";
  generate_string (enum_values, stream, indent + indent_str.length ());
  stream << " };";
  stream << "\n";
  stream << indent_str;
}
