/*
 * File automatically generated by
 * gengen 1.2 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "print_help_string.h"

void
print_help_string_gen_class::generate_print_help_string(ostream &stream, unsigned int indent)
{
  string indent_str (indent, ' ');
  indent = 0;

  if (shared)
    {
      generate_string (target, stream, indent + indent_str.length ());
      stream << "[";
      generate_string (index, stream, indent + indent_str.length ());
      stream << "] = ";
      if (last)
        {
          stream << "0; ";
        }
      else
        {
          generate_string (from, stream, indent + indent_str.length ());
          stream << "[";
          generate_string (full_index, stream, indent + indent_str.length ());
          stream << "];";
        }
      stream << "\n";
      stream << indent_str;
    }
  else
    {
      stream << "\"";
      generate_string (helpstring, stream, indent + indent_str.length ());
      stream << "\",";
      stream << "\n";
      stream << indent_str;
    }
}
