name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.0

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@v5.4.0
    with:
      cmake-options: '-DRTK_BUILD_APPLICATIONS:BOOL=OFF'
      itk-python-package-org: 'SimonRit'
      itk-python-package-tag: '26495c927f31ea20616efe2b2bad05e9275ea3a5'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
