name: Build, test, package

on: [push,pull_request]

jobs:
  cxx-build-workflow:
    uses: SimonRit/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@6cb76eec1085e32573f378a8763c606970df6c33

  python-build-workflow:
    uses: SimonRit/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@6cb76eec1085e32573f378a8763c606970df6c33
    with:
      cmake-options: '-DRTK_BUILD_APPLICATIONS:BOOL=OFF'
      itk-python-package-org: 'SimonRit'
      itk-python-package-tag: '45cfd02a22661731ca5b155f210cfa2f887d50e7'
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
